apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-platform-worker
  labels:
    app.kubernetes.io/name: {{ include "bot-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount.worker }}
  selector:
    matchLabels:
      app: bot-platform-worker
  template:
    metadata:
      labels:
        app: bot-platform-worker
        app.kubernetes.io/name: {{ include "bot-platform.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
    spec:
      containers:
        - name: worker
          image: {{ .Values.image.worker }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: bot-platform-worker-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: bot-platform-worker
