---
- name: Restart bot platform in order
  hosts: localhost
  gather_facts: false
  vars:
    # usar el mismo Python donde instalamos dependencias en el job
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

    # variables no reservadas
    ns: "{{ ns | default('bot') }}"
    restart_order:
      - api
      - worker
      - nlp

    # timestamp ISO8601 sin depender de gather_facts
    restart_ts: "{{ lookup('pipe','date -u +%Y-%m-%dT%H:%M:%SZ') }}"

  tasks:
    - name: Ensure namespace exists
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Namespace
        name: "{{ ns }}"

    - name: Trigger restart (annotate) sequentially
      vars:
        deploy_name: "bot-platform-{{ item }}"
      loop: "{{ restart_order }}"
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ deploy_name }}"
            namespace: "{{ ns }}"
          spec:
            template:
              metadata:
                annotations:
                  kubernetes.io/change-cause: "ansible-restart {{ restart_ts }}"
                  kubectl.kubernetes.io/restartedAt: "{{ restart_ts }}"

    - name: Wait Ready after each restart
      vars:
        deploy_name: "bot-platform-{{ item }}"
      loop: "{{ restart_order }}"
      retries: 60
      delay: 5
      until: >
        (result.resources[0].status.availableReplicas | default(0))
        >= (result.resources[0].spec.replicas | default(1))
      kubernetes.core.k8s_info:
        api_version: apps/v1
        kind: Deployment
        name: "{{ deploy_name }}"
        namespace: "{{ ns }}"
      register: result
