---
- name: Rotate a secret and restart deployments
  hosts: localhost
  gather_facts: false
  vars:
    namespace: "{{ namespace | default('bot') }}"
    secret_name: "{{ secret_name | default('bot-secret') }}"
    new_value: "{{ new_value | default(lookup('password', '/dev/null length=24 chars=ascii_letters')) }}"
  tasks:
    - name: Create/patch secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Secret
          metadata:
            name: "{{ secret_name }}"
            namespace: "{{ namespace }}"
          type: Opaque
          stringData:
            TOKEN: "{{ new_value }}"
    - name: Annotate deployments to restart and pick the new secret
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: "{{ item }}"
            namespace: "{{ namespace }}"
          spec:
            template:
              metadata:
                annotations:
                  secret/rotatedAt: "{{ ansible_date_time.iso8601 }}"
      loop:
        - bot-platform-api
        - bot-platform-worker
        - bot-platform-nlp
