name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up KinD cluster
        uses: helm/kind-action@v1.9.0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Install metrics-server
        run: |
          kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
          kubectl -n kube-system rollout status deploy/metrics-server --timeout=180s

      - name: Helm lint + install chart
        run: |
          helm lint ./helm/bot-platform
          helm upgrade --install bot-platform ./helm/bot-platform -n bot --create-namespace
          kubectl -n bot rollout status deploy -l app.kubernetes.io/name=bot-platform --timeout=300s

      - name: Python deps (Ansible)
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          ansible-galaxy collection install -r ansible/collections/requirements.yml

      - name: Ansible restart-platform (check mode)
        env:
          K8S_AUTH_KUBECONFIG: ${{ runner.temp }}/kubeconfig
        run: |
          # export kubeconfig from kind
          kind get kubeconfig > $K8S_AUTH_KUBECONFIG
          ansible-playbook ansible/playbooks/restart-platform.yml -e namespace=bot --check

      - name: Smoke test
        run: |
          ./scripts/smoke.sh
