name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up KinD cluster
        uses: helm/kind-action@v1.9.0

      - name: Set up Helm
        uses: azure/setup-helm@v4

      # metrics-server omitido: no es necesario (HPA deshabilitado)

      - name: Helm lint + install chart
        run: |
          helm lint ./helm/bot-platform
          helm upgrade --install bot-platform ./helm/bot-platform -n bot --create-namespace
          kubectl -n bot rollout status deploy -l app.kubernetes.io/name=bot-platform --timeout=300s

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Ansible deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          ansible-galaxy collection install -r ansible/collections/requirements.yml

      - name: Ansible restart-platform (check mode)
        env:
          K8S_AUTH_KUBECONFIG: ${{ runner.temp }}/kubeconfig
        run: |
          kind get kubeconfig > "$K8S_AUTH_KUBECONFIG"
          ansible-playbook ansible/playbooks/restart-platform.yml -e namespace=bot --check

      - name: Smoke test
        run: |
          ./scripts/smoke.sh
